/*
 * Copyright (c) 2026 STMicroelectronics
 * SPDX-License-Identifier: Apache-2.0
 */

#ifndef STSEPHYR_STSE_CONF_H_
#define STSEPHYR_STSE_CONF_H_

#include "stse_platform_generic.h"

#define STSE_CONF_STSAFE_A_SUPPORT

#ifdef CONFIG_STSEPHYR_ECC_NIST_P256
#define STSE_CONF_ECC_NIST_P_256
#endif
#ifdef CONFIG_STSEPHYR_ECC_NIST_P384
#define STSE_CONF_ECC_NIST_P_384
#endif
#ifdef CONFIG_STSEPHYR_ECC_NIST_P521
#define STSE_CONF_ECC_NIST_P_521
#endif
#ifdef CONFIG_STSEPHYR_ECC_BRAINPOOL_P256
#define STSE_CONF_ECC_BRAINPOOL_P_256
#endif
#ifdef CONFIG_STSEPHYR_ECC_BRAINPOOL_P384
#define STSE_CONF_ECC_BRAINPOOL_P_384
#endif
#ifdef CONFIG_STSEPHYR_ECC_BRAINPOOL_P512
#define STSE_CONF_ECC_BRAINPOOL_P_512
#endif
#ifdef CONFIG_STSEPHYR_ECC_CURVE25519
#define STSE_CONF_ECC_CURVE_25519
#endif
#ifdef CONFIG_STSEPHYR_HASH_SHA256
#define STSE_CONF_HASH_SHA_256
#endif
#ifdef CONFIG_STSEPHYR_HASH_SHA384
#define STSE_CONF_HASH_SHA_384
#endif
#ifdef CONFIG_STSEPHYR_HASH_SHA512
#define STSE_CONF_HASH_SHA_512
#endif

#ifdef CONFIG_STSEPHYR_HOST_SESSION
#define STSE_CONF_USE_HOST_SESSION
#endif
#ifdef CONFIG_STSEPHYR_HOST_KEY_ESTABLISHMENT
#define STSE_CONF_USE_HOST_KEY_ESTABLISHMENT
#endif
#ifdef CONFIG_STSEPHYR_HOST_KEY_WRAPPED_PROVISIONING
#define STSE_CONF_USE_HOST_KEY_PROVISIONING_WRAPPED
#define STSE_CONF_USE_HOST_KEY_PROVISIONING_WRAPPED_AUTHENTICATED
#endif
#ifdef CONFIG_STSEPHYR_SYMMETRIC_KEY_ESTABLISHMENT
#define STSE_CONF_USE_SYMMETRIC_KEY_ESTABLISHMENT
#define STSE_CONF_USE_SYMMETRIC_KEY_ESTABLISHMENT_AUTHENTICATED
#endif
#ifdef CONFIG_STSEPHYR_SYMMETRIC_KEY_WRAPPED_PROVISIONING
#define STSE_CONF_USE_SYMMETRIC_KEY_PROVISIONING_WRAPPED
#define STSE_CONF_USE_SYMMETRIC_KEY_PROVISIONING_WRAPPED_AUTHENTICATED
#endif

#endif /* STSEPHYR_STSE_CONF_H_ */
